#!/bin/bash
#description: Starts selenium-standalone

SELENIUM_BIN=./node_modules/selenium-standalone/bin/selenium-standalone
SELENIUM_PID=./var/run/selenium.pid
SELENIUM_LOG=./var/log/selenium.log

case "$1" in
  start)
    if [ -f $SELENIUM_PID ]; then
      echo "Selenium is already started"
      exit 1
    fi
    $SELENIUM_BIN start 1>$SELENIUM_LOG 2>&1 &
    echo $! > $SELENIUM_PID
    ;;
  stop)
    if [ ! -e $SELENIUM_PID ]; then
      echo "Selenium is not running"
      exit 1
    fi
    kill `cat $SELENIUM_PID`
    rm -f $SELENIUM_PID
    echo "Selenium stopped" >> $SELENIUM_LOG
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
